@startuml
left to right direction
skinparam linetype ortho
:User: as User
:Mentor: as Mentor
rectangle "ITLC Timetable System" {
  (Show timetable) as (UC1)
  (Add lesson) as (UC2)
  (Remove lesson) as (UC3)
  (Change lesson) as (UC4)
  (Search lessons) as (UC5)
  (Book class) as (UC6)
  (Check against DkIT timetable system) as (UC8)
  (Check currently booked classes) as (UC7)
  (Contact Mentor) as (UC9)
  (Monitor class attendance) as (UC10)
  (Track student progress) as (UC11)
  (Provide Online Resources) as (UC12)
  (Access online resources) as (UC13)

  User -- (UC1)
  User -- (UC5)
  User -- (UC6)
  User -- (UC7)
  User -- (UC9)
  User -- (UC13)
  (UC1) -- Mentor
  (UC2) -- Mentor
  (UC3) -- Mentor
  (UC4) -- Mentor
  (UC5) -- Mentor
  (UC7) -- Mentor
  (UC8) -- Mentor
  (UC10) -- Mentor
  (UC11) -- Mentor
  (UC12) -- Mentor

  (UC4) ..> (UC2) : include
  (UC3) ..> (UC2) : include
}
@enduml
