@startuml

Timetable "1" o-- "*" Lesson
Lesson "1" -- "1" Room : happens in
Lesson "1" -- "1..*" Mentor : taught by

Mentor "1" -- "*" Teachers
Teachers "*" -- "1" Subject
Resource "*" -- "1" User : uploads
User <|.. Student
User <|.. Mentor
Resource "1" -- "1" Subject : has
Resources o-- Resource
Lesson "1" -- "1" Subject : has
Lesson "1" -- "*" Student : attends
Resources -- User : uses

class Timetable {
  Lesson[] lessons
  addLesson()
  removeLesson()
  changeLesson()
  showTimetable()
  searchLessons()
  bookClass()
}

class Lesson {
  Subject topic
  String description
  DateTime datetime
  Room room
  Mentor mentor
  String recommendedLevel
  int attendance
  ---
  newLesson()
  approveLesson()
  ---
  getTopic()
  getDescription()
  getDatetime()
  getRoom()
  getMentor()
  getRecommendedLevel()
  getAttendance()
  setTopic()
  setDescription()
  setDatetime()
  setRoom()
  setMentor()
  setRecommendedLevel()
  setAttendance()
}

class Room {
  String name
  int capacity
  getName()
  getCapacity()
  setName()
  setCapacity()
}

class Mentor {
  String name
  String id
  String contact_detail
  ---
  notify()
  contact()
  ---
  getName()
  getId()
  getContactDetails()
  setName()
  setId()
  setContactDetails()
}

Student - Mentor : contact

class Resources {
  Resource[] resources
  addResource()
  editResource()
  removeResource()
  getResource()
}

class Resource {
  Subject subject
  User uploader
  String contents
  ---
  addTopic()
  removeTopic()
  editTopic()
  searchResource()
  ---
  getSubject()
  getUploader()
  getContents()
  setSubject()
  setUploader()
  setContents()
}

class User {
  String name
  String id
  ---
  signIn()
  getResource()
  ---
  getName()
  getId()
  setName()
  setId()
}

class Student {
  String name
  int year
  String Id
  Lesson[] attendedLessons
  Result[] grades
  ---
  notify()
  attendLesson()
  getAttendance()
  verifyAttendance()
  updateProgress()
  getProgress()
  ---
  getName()
  getYear()
  getId()
  getAttendedLessons()
  getGrades()
  setName()
  setYear()
  setId()
  setAttendedLessons()
  setGrades()
}

Student -- Result : has
Result -- Subject

class Result {
  Subject subject
  int result
  getSubject()
  getResult()
  setSubject()
  setResult()
}

class Subject {
  String name
  int year
  getName()
  getYear()
  setName()
  setYear()
}

class Teachers {
  Subject subject
  Mentor mentor
  getSubject()
  getMentor()
  setSubject()
  setMentor()
}

@enduml
