@startuml

Timetable "1" o-- "*" Lesson
Lesson "1" -- "1" Room : happens in
Lesson "1" -- "1..*" Mentor : taught by

Mentor "1" -- "*" Teachers
Teachers "*" -- "1" Subject
Resource "*" -- "1" User : uploads
User <|.. Student
User <|.. Mentor
Resource "1" -- "1" Subject : has
Resources o-- Resource
Lesson "1" -- "1" Subject : has
Lesson "1" -- "*" Student : attends
Resources -- User : uses

class Timetable {
  Lesson[] lessons
  addLesson()
  removeLesson()
  changeLesson()
  showTimetable()
  searchLessons()
  bookClass()
}

class Lesson {
  Subject topic
  DateTime datetime
  Room room
  Mentor mentor
  String recommendedLevel
  int attendance
}

class Room {
  String name
  int capacity
}

class Mentor {
  String name
  String contact_detail
  contact()
}

Student - Mentor : contact

class Resources {
  Resource[] resources
  addResource()
  editResource()
  removeResource()
  getResource()
}

class Resource {
  Subject subject
  User uploader
  addTopic()
  removeTopic()
  editTopic()
  searchResource()
}

class Student {
  String name
  int year
  String Id
  Lesson[] attendedLessons
  Result[] grades
  attendLesson()
  getAttendance()
  verifyAttendance()
  updateProgress()
  getProgress()
}

Student -- Result : has
Result -- Subject

class Result {
  Subject subject
  int result
}

class Subject {
  String name
  int year
}

class Teachers {
  Subject subject
  Mentor mentor
}

@enduml
